apiVersion: v1
kind: Secret
metadata:
    name: plarza-worker
    namespace: plarza
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:mJWtcYlbVDKhuda0ni5C6xa+0M0vvO4VZCyit8Q+7GcXTNMjrUbKpaT9MUuZDU5tBR45zWfQy+Agw+/86eqPrA==,iv:ca6yBGhHLsGYacz236rEr4bE3zHVrVQykrjYU/Q7R84=,tag:ikfc9YMmmBDjOM+lM6lgpQ==,type:str]
    EXTENSION_API_KEY: ENC[AES256_GCM,data:0BkxcigxGCJ+x2QCNkPOPuUqRjnSQWuTX+RXW9MLI3L/ljmH3crgH4hikc2+6ijs42n/gIK59yfyYt0K/oCUjA==,iv:v6E2HhA5oaVm5FZhYokzpf6Dm/tSSOLZSVT+7k0+Np8=,tag:6BUhoLpS9m4K1bgP8EvVJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKd1J6VzNJdDRBQWxXckNj
            Q3JrYm9sei96N3dYQmJ4eXFqZm1CSXU0enlvCi9xS3d3cGloVkoyUVlEOXFTdWw2
            SmFpUGw3c3hERzZQMFEzTFlOdXN0OXMKLS0tICtPS2Z5MmhLb3E1RDE5eHI0T21X
            RUFPbmoxZDBvRHJPdUNOT0tMZWJnb2sKqdIKGKAcC1ensUY4bi+UGBfhs0vWmy7F
            JkGz6foXEVGL7Wpuke0ti7aSqlxY54Ojz/X8Z+gunJKStO7o4cxA5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T04:12:56Z"
    mac: ENC[AES256_GCM,data:cLC0x+2Nijru98txsj+wGgojd2hrVFgrQaR68tvPgzwzHV6J7FcD28yJFe1g2sB7qFfN6E40iwGjyfG/xclMB8dzSsTG8csX87rqVJQyn8osWJ3Ksc1iOWAzLUH6ogEzFAbhpZbix2gbi32deNeXAO39asLaKlAzpVLbwE8nm2A=,iv:enqn2hf2uW+fDVGLhQuxtQY8TJg8UDCCRJLVazAqQXA=,tag:TFWKYXicr1fux2xuhk8c1g==,type:str]
    version: 3.13.1
