apiVersion: ENC[AES256_GCM,data:T+c=,iv:Ac5fSnYwjiNNnNCnd9+DIRylLsm8ZLmkCKnKhS1nkUE=,tag:1u0Pnlat8wonf4B7MeJARA==,type:str]
kind: ENC[AES256_GCM,data:+Vgvt/qK,iv:GTeXQa3sxQPATRf+XRDYHm7u+RImxL+POWX/MI7Kf+I=,tag:JrvEWhFrQAy2H5ndMJp3xA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3JwlgQM0+MJE7/1j7g==,iv:mJIfkfO05Kf1y9WJ1nr5Zx+K+GOzK22Nix45MacPsOU=,tag:j45ljRNcXLsApINhzya2nw==,type:str]
    namespace: ENC[AES256_GCM,data:lC5VwK6s,iv:IT+rHkf9d5RRNGyHeDjPgnD2u6D5GerHmJ9bpcSedK0=,tag:e3W9NHE56mmLWy2zm1tkpA==,type:str]
type: ENC[AES256_GCM,data:lUD0HYdI,iv:n+o9Jd+656zOzbXHqQZvlzswv4zdhl4NHGJS6SwWVUw=,tag:1qtVfvKS8kwDj5qC5dVzbw==,type:str]
stringData:
    API_KEY: ENC[AES256_GCM,data:7AxZqRa916SvlJQwlP9sS0jhC1FHY9BPHzEFNo9GVLp6hcCltwY/D50IHBFMOaNol1qCeW0QqFJTcdcGvLPfMg==,iv:Qhapd8OMQx8AToMc/KQUnXs70UlygUNuRWULrsyNuxo=,tag:B1Dh6tUOQ6ncu0F5idGkjw==,type:str]
    EXTENSION_API_KEY: ENC[AES256_GCM,data:m+71nCliPNpQ7Mzo7Qo4p/xlFdrBL3T3nKBRZw6aHmRWt0LpE06hEED1cDLeVuJSl8tEm/ZFsmD0DfbDcAYFNQ==,iv:GAVbmmpf58mxW3hFOdF9YzkfeGvfDTbphnSE/vwdHSg=,tag:5Kl7iz1tKceuSuqUJffnwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZmxoTFJNcnJhWnQxL2d5
            Y2FiN1hKdnRQdm8rZituMjVOZlJMalFBMXk0Clo1L1RyYkFRRXZRZlJYVVl3SW4w
            VmptWk5vRGloWkxyTzhMTzRQUnFIeGcKLS0tIDIrMDlwU2taSHk4MU1RZ25OZ0VH
            encwdnY0OHpaSytvMnlqY3o1WVUrVDQKixP+SuewLi/NN6TWT3ydNuq69s5ADuqs
            Jd8kxSHqKSpE6eu10dcD4ZZ3jkCFG65DTNob/pVvEAX6SouRmNMRxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgnp0qs4w0yyy6r8shpjea6tepyygdj4xr2wvx8dkg9af7te648s9drfsm
    lastmodified: "2026-07-17T02:50:04Z"
    mac: ENC[AES256_GCM,data:HkElnEPIKh1NzxImx3UDSg3oISUSFeEAV+j2idkIoTKkZnslYx63OUDKeARel55ThiZaVe4noNsWP3RToontp4VvsePVLrMRGOBoCTHZXht/b1kFRJt+UNUKnFTv3qDGX+WmOcZXJ0ykamJvVR4fQ27zXxHeanfAPPwHs+p3Ni4=,iv:Czq7dONYFqwQnZbzaMtonApt0YMi3dh8UcuwgmnL9cs=,tag:b8wFbbZLIwJGnN3FTT7JNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
