apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps/secrets.sops.yaml
  - apps/plarza/ghcr-credentials.sops.yaml
  - apps/plarza/secrets.sops.yaml
  - apps/plarza/image-automation.yaml
  - apps/plarza/manifest.yaml
  - apps/worker/secrets.sops.yaml
  - apps/worker/manifest.yaml
  - apps/libsql/spinyourlife.yaml
  - apps/spinyourlife/secrets.sops.yaml
  - apps/spinyourlife/manifest.yaml
  - apps/immich/postgres.yaml
  - apps/immich/repository.yaml
  - apps/immich/image-automation.yaml
  - apps/immich/release.yaml
  - apps/tuwunel/manifest.yaml
  - apps/paste/manifest.yaml

configMapGenerator:
  - name: immich-values
    namespace: immich
    files:
      - values.yaml=apps/immich/values.yaml

generatorOptions:
  disableNameSuffixHash: true
