apiVersion: v1
kind: Secret
metadata:
    name: spinyourlife-ghcr
    namespace: libsql
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:gKmwNVNa+bXvOLnohkrqTgwZw2oFNRupIpP1PW26vwW5qWUWLkazNGYKj9gvupHoH38XnpwX/SzovwrB4i7GgD85CcqF81uXbmOWBSLf7zwDVUAYPeX69ncxfUe+hnRfgdLQ7aSFb4fy/VcWsybFhkW64FbGIICsrDJGfY7o/UVSKAJQauuxMu9LX7qGjtbKGOcIbHuEZsocuR9cNNDkv5mjIQbUC0SpEyZzyXyjkXwsQ8AsqFTXkXobRP1tLpeWnrx4GMmQ9skv9saLhdcMgmjQg5iEHv+Axn+59fxKnox4VMdt,iv:izlY7lJg7Y2fSZ7z5KUI0ouHmnpqiz4JCGFVoEfDOvs=,tag:iMGqNupyX9E3E1JfzSbd7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcjVncWc2UnpWd2gyeEd4
            OFNUREpXUlc3ZWx1VWE5UXVNbW1FM3ZaN0hvCnByeHQxQ2NEYWw2Z0pwOHo1Tkc1
            SlhMeFp6YmpWU2lQZTVwTjd5QVlyM1EKLS0tIHlOT0FaR3BtVVdsUkNPRTI1VWRr
            RERkUTJlNkMzM2pkeVNZOHBFZW91a3MKQ/yfzur5AJuW7cKwbsEjOAeJhCxUZzi8
            YgeYH1JmSwV4z4W8lecDanzM2LgRpc8WpjKSzuP98+zT8GiQhoW1iQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgnp0qs4w0yyy6r8shpjea6tepyygdj4xr2wvx8dkg9af7te648s9drfsm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T04:03:30Z"
    mac: ENC[AES256_GCM,data:bgVNx9HyPiX28Fn8nL3YzvTdQ6aH4c2S3XtRtc/lP7frOf8GffyGJmiM3KBeYgd+kDpMzBUiHA/HPC13KbsXQ1A223nScnSYSi+c8Ky3///wgR70yg8CWPy0mjvIon2q2Ssl/VnAdlP8HK8NevoNlqe4lc6OQ2KJsTdlgrzj8J8=,iv:tpxxNIlsyOZs1Ps0IS2CQpoBXK47Pz1LgAotBKMTT68=,tag:cTIFkCv0++sfTbOsLse/og==,type:str]
    version: 3.13.2
