apiVersion: v1
kind: Secret
metadata:
    name: spinyourlife-iap
    namespace: libsql
type: Opaque
stringData:
    APPLE_IAP_PRIVATE_KEY_B64: ENC[AES256_GCM,data:AO9X53nJHlmycIa8NrhP6P/uIILaPPD895h9thsIFEIhccRi3SRvjCP+Q2xAXGGmIpn4DBGiRsKplVmmApQ8yj9M+ijeNjxpoHxi8QV3227WXYYQlHndrBjIw/lLKEqqyHmPHAjqq3kFrevSpIiD00SUFVtPNt6BeUvHRRxcFw9itP01C1BQ8RAknvOVXlBcSia8mwk7Vwdb9xYA+2BOoDJMRX33cfcC8jH6kHMaJ61fkOe4BnC16Pq1EFWY47r1wPQ/CiEE8iUyZFZb2rVEZTrzHNKEETO45ThDuSV7f4TOr5pSRJWYnE8Eufv26Neu/df4FLPXZOjjfXXtmjTv3qVaXZOpcIjOk3hc7APppqY7xz5O/7m6DiPF3klbQIuZCl85GbcLvSfdlTaz8EDtYLLg7MHYTBPku+7DDqdEWiVjngzD0tmxil//U+3OHS32mYG4a7iusjY=,iv:JYfn0gtLcw0uhzvychW7BAEa5t+lDhIEYQTf/t4W0KM=,tag:UYYjl2eVNTfjiZbEoZmzFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVFJzOERUN2NUSFdqMlh1
            VDBBR0JUbXJNWWU1NU91WnlaYXhzbTNGMDJVClR0N2VueTBLRk9tcVN5OUdUbzIy
            cHM3SGNUZGhUNmN0eWIwL01GKzlBNzAKLS0tIFhQQ0FFQ1dLUVF2SE1QRFZrR3k1
            Q25RVG52STVnVTZCSlM2RDdTQVIwOXMKdxAU8u5+XV85LADb/dXz7tkCvazqOaUF
            1vouR053Y09RxnMAZBxG0U1fmJP1RFDXMSAfSUA15vUJOHAUHjp8RQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T04:39:54Z"
    mac: ENC[AES256_GCM,data:hwJPmGXrVhBeYMpySucATo2xig0C8DrhrHEX945QmiZmXwPrhlxQYSYvzXOTG2rBDI4wKUTAX7oGbYRGuGCzrzBF/+pbm9o4UcPlHWSuXk9My4jSoM1dvIvgeXSCRsrBFVBz0ZNzC3DRVnduNaKM3QbND44P+V1IxsdWqTk73OM=,iv:W7iMDm3xJntbYoNeoOYcnxV1sAHq1wOtfYFcDqFbAzw=,tag:OO6BL9rScez9PQ4epfyayw==,type:str]
    version: 3.13.1
