apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
  ref:
    digest: sha256:901a00064286b446e723bc145f015470424551ea2ddd8714058eb56fc53d4939
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 30m0s
  releaseName: flux-operator
  chartRef:
    kind: OCIRepository
    name: flux-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
  values:
    priorityClassName: system-cluster-critical
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 512Mi
    web:
      enabled: true
      ingress:
        enabled: false
      networkPolicy:
        create: true
      rbac:
        createRoles: true
