apiVersion: ENC[AES256_GCM,data:gwA=,iv:oPZAO8NhMfK9nptju+8n0dlK32ARVL59fhYVge9lEHI=,tag:nRYtchV2/2k5sIA+a8cGdg==,type:str]
kind: ENC[AES256_GCM,data:qANcEyon,iv:qd4R0hdbzcoIFcc5VIoIYSVhj+Ji+kj7oGrQb4WNZko=,tag:FcHKaBfxyZjlk8n0CBj3Fw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Pe6KntFB07FdWJu1KYqh8A==,iv:E2EEWeX65Gfcha/K8Wxi0LKDurtXXdDn2fDnSB8Fi0o=,tag:Vj7FPujACuNFNCwy4wyAtg==,type:str]
    namespace: ENC[AES256_GCM,data:YAYP2jZQ,iv:rL9tLyB+jwXoDjqkzJaY7z/eV3gHIdR1TzrWlISPn3M=,tag:XqFhW9BXNOgyfDn+9MV1Ig==,type:str]
type: ENC[AES256_GCM,data:IXmlpwkw,iv:VffqLf0uS11lLpHniBoAyC3H3vL30p6ugl5MWSqXJpM=,tag:2rITBiChsqXPyjE8FJhSEA==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:6ERHBPhaHafQDrxIhJTTWmb1g9m063/p/Epa2ivPDvGRqqLAn6yNvlz4j3JyNFFZnT02qJ6bkaN4KZ46MVmUGA==,iv:xiSs/wNmRT94U72bXcAt5fPdYXQ92ueHeg90ue+8qvo=,tag:D6jRJ3UINxD+GoVem83/VQ==,type:str]
    password: ENC[AES256_GCM,data:07O9vp2fTmXpB2TOf7iuiLeQhUZlzhEOebQ7dPjWK57YGXNbh+R094INMLRwZa8qZP6lwl9Y8KGUeY57rIo3+A==,iv:x+AzBJYPbBRmO9kPyLLUqRGHDvO6kjEsNi/cv8Ar7Zk=,tag:mlMMBHHyG4uzjjkTt41CWw==,type:str]
    replication-password: ENC[AES256_GCM,data:S3A9xnlrUq/Qf8ACvCIZCoavwKBNA4CiOg5appZecjJGSwhtsczSJK0UEKCKT1+jXOD0k21grbeHUhc3floCrw==,iv:EZ7coiPI3wgoREDV0jyAINSTietMWYuNDSuS+QQm6jw=,tag:P/0gNcnpe01TYlRMHLVAZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbzNuYmo3NE9odm5nNlBw
            eHlXczFKNmFSZksyVkEvN2IrL0RweDNKbHhvClE5WDFrZE5uZkJackEzbkRrc21E
            N2dvQ1ZrR2Jrd0tqZVp0aXQxaW8yODQKLS0tIFdvOWNlVjFZOFB5cURSZkxQTVp0
            VHo4UVdRTkdoVnhBR1ZzTjI0KzhaV0EKjCcp9b8otZsu/8T6OdwoS7Y8NsdfSw00
            1msN3Cttkw5hZbZk32XEJGK4x+fjld5STbm87jnL/lV31B7PgioGCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgnp0qs4w0yyy6r8shpjea6tepyygdj4xr2wvx8dkg9af7te648s9drfsm
    lastmodified: "2026-07-19T03:42:51Z"
    mac: ENC[AES256_GCM,data:oB/pgKqRmAwTuzFwqC8XfY1otCj2OBLZ5cATNSNosMvEXXGTAo2MkG8tDX+f0WpHqRJf4TIHHHNRJtqJJTaWQI5I+upADdVSVMlJ6SdGHfB/wq60AnPmr4lkeiJjjyxVncdHe38tsGSdO2R12l4rjM8ofPkuJqJdDXndr7k57do=,iv:B6jujrkYlKcE/MZFCNtdlxtZZEQg6mlrVbwCYIbYQO0=,tag:B/ecyhfTK0jDKhoZPbHk0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:gwA=,iv:oPZAO8NhMfK9nptju+8n0dlK32ARVL59fhYVge9lEHI=,tag:nRYtchV2/2k5sIA+a8cGdg==,type:str]
kind: ENC[AES256_GCM,data:qANcEyon,iv:qd4R0hdbzcoIFcc5VIoIYSVhj+Ji+kj7oGrQb4WNZko=,tag:FcHKaBfxyZjlk8n0CBj3Fw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4wcX5yNgsD8hVVfTcc27TZyJzw==,iv:omce9WNEGvSbtZorKByID9q501Cj1YJLh/r+Vd/N0So=,tag:dk9hv5kAJhF90y5IA1Ei5Q==,type:str]
    namespace: ENC[AES256_GCM,data:YAYP2jZQ,iv:rL9tLyB+jwXoDjqkzJaY7z/eV3gHIdR1TzrWlISPn3M=,tag:XqFhW9BXNOgyfDn+9MV1Ig==,type:str]
type: ENC[AES256_GCM,data:IXmlpwkw,iv:VffqLf0uS11lLpHniBoAyC3H3vL30p6ugl5MWSqXJpM=,tag:2rITBiChsqXPyjE8FJhSEA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:bUTbEyIUHKcKsyin85HswRs6kOagahth7WiU/n4rqVyM3fqC1hMmdN91YhPw7n+P5pe43Evt68yMknZAmQx/7w==,iv:Qjz1QdouOK7flQ1o+AwYsV3xH1j2c7l7SqEZN61QooM=,tag:M2DVGPWQpVT6yB2hU54YGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbzNuYmo3NE9odm5nNlBw
            eHlXczFKNmFSZksyVkEvN2IrL0RweDNKbHhvClE5WDFrZE5uZkJackEzbkRrc21E
            N2dvQ1ZrR2Jrd0tqZVp0aXQxaW8yODQKLS0tIFdvOWNlVjFZOFB5cURSZkxQTVp0
            VHo4UVdRTkdoVnhBR1ZzTjI0KzhaV0EKjCcp9b8otZsu/8T6OdwoS7Y8NsdfSw00
            1msN3Cttkw5hZbZk32XEJGK4x+fjld5STbm87jnL/lV31B7PgioGCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgnp0qs4w0yyy6r8shpjea6tepyygdj4xr2wvx8dkg9af7te648s9drfsm
    lastmodified: "2026-07-19T03:42:51Z"
    mac: ENC[AES256_GCM,data:oB/pgKqRmAwTuzFwqC8XfY1otCj2OBLZ5cATNSNosMvEXXGTAo2MkG8tDX+f0WpHqRJf4TIHHHNRJtqJJTaWQI5I+upADdVSVMlJ6SdGHfB/wq60AnPmr4lkeiJjjyxVncdHe38tsGSdO2R12l4rjM8ofPkuJqJdDXndr7k57do=,iv:B6jujrkYlKcE/MZFCNtdlxtZZEQg6mlrVbwCYIbYQO0=,tag:B/ecyhfTK0jDKhoZPbHk0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:gwA=,iv:oPZAO8NhMfK9nptju+8n0dlK32ARVL59fhYVge9lEHI=,tag:nRYtchV2/2k5sIA+a8cGdg==,type:str]
kind: ENC[AES256_GCM,data:qANcEyon,iv:qd4R0hdbzcoIFcc5VIoIYSVhj+Ji+kj7oGrQb4WNZko=,tag:FcHKaBfxyZjlk8n0CBj3Fw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:d7nr0StlY0vVoY1Fv3g=,iv:R4iMZ/OsKJLZiizk92G5LMDludZJoNlRPUfzwsD/vBI=,tag:8K2LN98iCXXYV7FtGnc+EQ==,type:str]
    namespace: ENC[AES256_GCM,data:LrigKB4Kog==,iv:lRQF4lCAZfS+p3jDqYJUOHVCOPun2+b8xelE9gnS65o=,tag:Nw9QSS1wrhJC0KmMmELSkw==,type:str]
type: ENC[AES256_GCM,data:IXmlpwkw,iv:VffqLf0uS11lLpHniBoAyC3H3vL30p6ugl5MWSqXJpM=,tag:2rITBiChsqXPyjE8FJhSEA==,type:str]
stringData:
    TUWUNEL_REGISTRATION_TOKEN: ENC[AES256_GCM,data:eg7iSM7JnVNNiGt/1i9S8Ffq9mwi8US2ZnI1vLIHdO/q3oaEDpLOrFSEW0208Idv6Kfmv9JVeCgcwJ6v13r7qg==,iv:2RYYwf8rzbWG+mPtqLwNtecrBxQKaMo76nWobPr57AU=,tag:sLeX9pB9bUtbPUo5Cqh9GQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbzNuYmo3NE9odm5nNlBw
            eHlXczFKNmFSZksyVkEvN2IrL0RweDNKbHhvClE5WDFrZE5uZkJackEzbkRrc21E
            N2dvQ1ZrR2Jrd0tqZVp0aXQxaW8yODQKLS0tIFdvOWNlVjFZOFB5cURSZkxQTVp0
            VHo4UVdRTkdoVnhBR1ZzTjI0KzhaV0EKjCcp9b8otZsu/8T6OdwoS7Y8NsdfSw00
            1msN3Cttkw5hZbZk32XEJGK4x+fjld5STbm87jnL/lV31B7PgioGCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgnp0qs4w0yyy6r8shpjea6tepyygdj4xr2wvx8dkg9af7te648s9drfsm
    lastmodified: "2026-07-19T03:42:51Z"
    mac: ENC[AES256_GCM,data:oB/pgKqRmAwTuzFwqC8XfY1otCj2OBLZ5cATNSNosMvEXXGTAo2MkG8tDX+f0WpHqRJf4TIHHHNRJtqJJTaWQI5I+upADdVSVMlJ6SdGHfB/wq60AnPmr4lkeiJjjyxVncdHe38tsGSdO2R12l4rjM8ofPkuJqJdDXndr7k57do=,iv:B6jujrkYlKcE/MZFCNtdlxtZZEQg6mlrVbwCYIbYQO0=,tag:B/ecyhfTK0jDKhoZPbHk0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
