apiVersion: ENC[AES256_GCM,data:0Wc=,iv:dlq45woH8SYQ7EUZlkhoXqa02zCMaVDlK5i4z1zEk4Q=,tag:5Uuot+ui/Bz6tdyamnykNg==,type:str]
kind: ENC[AES256_GCM,data:NF+B4V/g,iv:AWTKcp+L39t7oqT432cBlUPCqDKdmJ9uqO3IBZ71/rA=,tag:e+26BuS/ISz9JzyXLP0aSw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4AIg62mTFjTvaPY=,iv:a99u/9a6FaeKKv17voisIKDTv/dbLEWVW+noElVqgJs=,tag:j+F6ETuypRIDMijG/4TLew==,type:str]
    namespace: ENC[AES256_GCM,data:wkfo6qUA,iv:nJt2OpUUa6X6whVcC1EhASPCZIoDqQG5Mr1CyCZe2wU=,tag:fbYwmgiAJn3U3kDbCmC7Lg==,type:str]
type: ENC[AES256_GCM,data:q0NepzOa,iv:P+I/x/sKK7CRGcL2ZimodUuy5Jqh8Ay9mdfxXBWKqKI=,tag:7eWPteXVWZjdCHhg5WlpXQ==,type:str]
stringData:
    SQLD_AUTH_JWT_KEY: ENC[AES256_GCM,data:/SWwzwGgmRKkUVsC+an91Zt5KCwWtLzY/cRPChxG2LmyI8ARwo2vRmOc0Q==,iv:7J3hhxX2Q56E8ndlmnAA0rt27O4CXvKybru3HPvuc9M=,tag:SHHS2DhJGEsEGYVWMzi1LA==,type:str]
    SQLD_AUTH_JWT_PRIVATE_KEY_PEM: ENC[AES256_GCM,data:VaUXrMBDvZcnM4r+X6+ol8rMbSp3WpHvA4FCg8vGRU1617JBdlpmLhLT8JzlppEFRRxMDOLzCLHyu1lmIqJO+aYlnL2fElT13tl3uQPhQ03JxMzT//5xz1OReNa5BEpeq8UvWJEfpyTwQM6OmjXkoAz2x9vU+w==,iv:B4c/SjEcJ4YsQL6HglXJd/l5OfGPBoOQubTQMA4c7Us=,tag:LeShVqd5n1OcvWY1tF55Dw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNU9QNEk0dkhDd2ZCemJT
            UkRlZStvUkd1QUJxUWFmdjU3MXR3emxDWDBrClU4NVQ0SVlCOC9neERGYnd1azZp
            eHBnc2plN0JlVlpHWk1sMnBGQVZpZ0kKLS0tIGloYUU5NjltRkV3bERENGlNYzMv
            ZFROOXVUL01jbDg1V2FiWm9ZNGRLaTgKTC6RAuIdNes0uhUYJ36oQmX+YpXasbk8
            WaFaBd3wN2yDwoo/Jn4WB0TLdcrQtFH4MEee9uxcr7QI2jtMPAJ9PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    lastmodified: "2026-06-10T08:06:08Z"
    mac: ENC[AES256_GCM,data:U2Dkv5og5lq8EpHr+4IQOyXCvhPB0Jtjck1duW/stxvhil9/Mrsfdf0ofSexShZsfkZbtlkNVxldlxcDB+Hg8qgc+ggb9C1udPheKrJCaQA37DB9OC7+IPc/fyvw5HC0IHTgumtp2DJMOfAyShrOf8fZEdFk10SB7c6a3IDUlo4=,iv:hUaHyV29oaLzVj172KsBvuEjwKgKfOHc9Q3Qf/wedSg=,tag:u99SdZjXmPcNuol3d7+hbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNU9QNEk0dkhDd2ZCemJT
            UkRlZStvUkd1QUJxUWFmdjU3MXR3emxDWDBrClU4NVQ0SVlCOC9neERGYnd1azZp
            eHBnc2plN0JlVlpHWk1sMnBGQVZpZ0kKLS0tIGloYUU5NjltRkV3bERENGlNYzMv
            ZFROOXVUL01jbDg1V2FiWm9ZNGRLaTgKTC6RAuIdNes0uhUYJ36oQmX+YpXasbk8
            WaFaBd3wN2yDwoo/Jn4WB0TLdcrQtFH4MEee9uxcr7QI2jtMPAJ9PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    lastmodified: "2026-06-10T08:06:08Z"
    mac: ENC[AES256_GCM,data:U2Dkv5og5lq8EpHr+4IQOyXCvhPB0Jtjck1duW/stxvhil9/Mrsfdf0ofSexShZsfkZbtlkNVxldlxcDB+Hg8qgc+ggb9C1udPheKrJCaQA37DB9OC7+IPc/fyvw5HC0IHTgumtp2DJMOfAyShrOf8fZEdFk10SB7c6a3IDUlo4=,iv:hUaHyV29oaLzVj172KsBvuEjwKgKfOHc9Q3Qf/wedSg=,tag:u99SdZjXmPcNuol3d7+hbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
apiVersion: ENC[AES256_GCM,data:qzk=,iv:WvgrgwevJ+dSVx8bacook6b2trXwDm8zB/yZ95K+t+E=,tag:yPXA5A0tCNpsGvTRxWzacA==,type:str]
kind: ENC[AES256_GCM,data:a1BByOe3,iv:CNvw70sLr4LyMjVVupmpKV0Z40iftB3q3u9FKX1zN0w=,tag:evkimUz6CdTjh4GD9rmE2A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CRBL4OX5KxYGdA==,iv:S+0uasS22KNZSqy7nXWYF1ctTLIFAOSxjuXQjDo387E=,tag:Wcq8C+gifm5sO9dnfGKS/g==,type:str]
    namespace: ENC[AES256_GCM,data:vvnREIs+,iv:r0oEH03IK5yvfsXyVxSCdvSk3wfUfDlc6PB4qmo4oX4=,tag:Y2RvBpoZDCn4uYsLogdSAg==,type:str]
type: ENC[AES256_GCM,data:kK/310A9,iv:auehnfvmhx5QClqprMLD3WuCz5kCUDq2OanqecjkQ6Q=,tag:p40uHM6PMc3Wrf9fvpfEzA==,type:str]
stringData:
    KOPIA_REPOSITORY_PASSWORD: ENC[AES256_GCM,data:I3mJc2U9VOPjFJDFDdhs7/ShIZYFwHlmxkOxxWUCSH6QC/0fDVzfnM5Xp04BRTSyUj/Vhz3DXoiOOV3R0yLwBQ==,iv:WXmklrH1i0vYn3PIBi+DF2oZsTo2mXOr6e/AHlfGUQU=,tag:fWR3tWgECQeh4nSN+ebgpA==,type:str]
    KOPIA_SERVER_HOSTNAME: ENC[AES256_GCM,data:DBl9UP2FUqixjSWQs7rJ+74=,iv:ySaX7gL1TnV/g2aieNsP71hY6bA2b+tyNC9c4jFWk9k=,tag:4TGcxOp+/E6g/o/vgdPtBQ==,type:str]
    KOPIA_SERVER_USERNAME: ENC[AES256_GCM,data:DUBuThyhi1I3jsQsncmqatYY0V8rrYPaZ43RiTAbfweChy4amrPEt51XG9jPJReJhHwnmFdR9baMRQC9/Lho2w==,iv:wZSzXyfSAfe5kVk9SmxUPE4tk0+Kim1nc4cNC4kpk+Q=,tag:s19Nv1EyBW5nNvuilRZj7A==,type:str]
    KOPIA_SERVER_PASSWORD: ENC[AES256_GCM,data:2MmYtSwXPZJ5VtVlEbyVi1MgQVckEsJwHjCLWAKpw3zYa4c5VoYEUHv9Eaw3th3+0Hehi9P/H2dZigpSE/rwlA==,iv:4cW67Vt6WrrmV8AzoZ4nOUCJHLq1lYCyT9aNeLfAVEI=,tag:7qsYsMxp238QyRLDQBUlPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNU9QNEk0dkhDd2ZCemJT
            UkRlZStvUkd1QUJxUWFmdjU3MXR3emxDWDBrClU4NVQ0SVlCOC9neERGYnd1azZp
            eHBnc2plN0JlVlpHWk1sMnBGQVZpZ0kKLS0tIGloYUU5NjltRkV3bERENGlNYzMv
            ZFROOXVUL01jbDg1V2FiWm9ZNGRLaTgKTC6RAuIdNes0uhUYJ36oQmX+YpXasbk8
            WaFaBd3wN2yDwoo/Jn4WB0TLdcrQtFH4MEee9uxcr7QI2jtMPAJ9PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    lastmodified: "2026-06-10T08:06:08Z"
    mac: ENC[AES256_GCM,data:U2Dkv5og5lq8EpHr+4IQOyXCvhPB0Jtjck1duW/stxvhil9/Mrsfdf0ofSexShZsfkZbtlkNVxldlxcDB+Hg8qgc+ggb9C1udPheKrJCaQA37DB9OC7+IPc/fyvw5HC0IHTgumtp2DJMOfAyShrOf8fZEdFk10SB7c6a3IDUlo4=,iv:hUaHyV29oaLzVj172KsBvuEjwKgKfOHc9Q3Qf/wedSg=,tag:u99SdZjXmPcNuol3d7+hbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNU9QNEk0dkhDd2ZCemJT
            UkRlZStvUkd1QUJxUWFmdjU3MXR3emxDWDBrClU4NVQ0SVlCOC9neERGYnd1azZp
            eHBnc2plN0JlVlpHWk1sMnBGQVZpZ0kKLS0tIGloYUU5NjltRkV3bERENGlNYzMv
            ZFROOXVUL01jbDg1V2FiWm9ZNGRLaTgKTC6RAuIdNes0uhUYJ36oQmX+YpXasbk8
            WaFaBd3wN2yDwoo/Jn4WB0TLdcrQtFH4MEee9uxcr7QI2jtMPAJ9PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    lastmodified: "2026-06-10T08:06:08Z"
    mac: ENC[AES256_GCM,data:U2Dkv5og5lq8EpHr+4IQOyXCvhPB0Jtjck1duW/stxvhil9/Mrsfdf0ofSexShZsfkZbtlkNVxldlxcDB+Hg8qgc+ggb9C1udPheKrJCaQA37DB9OC7+IPc/fyvw5HC0IHTgumtp2DJMOfAyShrOf8fZEdFk10SB7c6a3IDUlo4=,iv:hUaHyV29oaLzVj172KsBvuEjwKgKfOHc9Q3Qf/wedSg=,tag:u99SdZjXmPcNuol3d7+hbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
apiVersion: ENC[AES256_GCM,data:Ee0=,iv:Gr3C9zHHRpMCAcdCCG4/hU+SKD82mzsfaigsAS/raEU=,tag:TTMXyFx4wE4M1ZIs2PCrMA==,type:str]
kind: ENC[AES256_GCM,data:wAVoibSC,iv:bntsCL5x0tkkV1GecXb4tmOQZGND8MHWXPcDxiH0d9g=,tag:lCdtPpQlH9Xtq4dSRsLYPA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Hz1RGCkbmqO/ZJ7d6bf5xw==,iv:7elvYvQRTiY4qvcQoNCuK2PIV8w/4IcXwY5KEnoBkxg=,tag:He7bbjZoeyQuQ8qkGX8o6Q==,type:str]
    namespace: ENC[AES256_GCM,data:VrPTk/8c,iv:UBV6LIq7/sEWJ6SHmlKPHGleKiwyaKhBogPeR1r5Pog=,tag:6r2Mk+uStmfyfZqJaoI5pA==,type:str]
type: ENC[AES256_GCM,data:VAKawOoY,iv:hvsMWTrFeDlTM6ZSs/271fbAIUH+tI6QM2JQICXmP9E=,tag:C8mm/UcQMxJenHTWYaCMcA==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:k/pRdGTeUr9sjJ4XzdipKdQuLSs/y/HhmPWmPOAhL6fvjXcOBJijpGx1Qaljq3snur6cOG8AVUvMMzHV7oiRQg==,iv:hYh+6rbsEfFWeBci1VvB2T7Rt2etDuF85L9sM3A7/ps=,tag:ueJUjtR+P/AMryNfxHLG0A==,type:str]
    password: ENC[AES256_GCM,data:58TBAi41LpZ/uLsTPtU3LITmUuyNnOeytWNz4pKlaWxKo7YY/+Ctcw37+c7rcI14HNb/W3EgEqEbK+gzUlmqdQ==,iv:ACeMD97/ndtIXKL8VbxVy6nxSRmXE4T9bw3nzSRNUzE=,tag:JRhaoJr6C6VIDOEqMmN1ww==,type:str]
    replication-password: ENC[AES256_GCM,data:8M4gJAgZRoo7WOBMD1sTY7ForYxh20IVX2+SME9JZbN7+mtf5cz+s4iFkL95Yc0CfszsfKZ3PvtrX2DwGsRMeQ==,iv:BNhZeoq2U1BZreaTRCbJiY4/rJQlxfMybMoifvFAcvI=,tag:lMVlOmAY+tIgzgxWU5JDHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNU9QNEk0dkhDd2ZCemJT
            UkRlZStvUkd1QUJxUWFmdjU3MXR3emxDWDBrClU4NVQ0SVlCOC9neERGYnd1azZp
            eHBnc2plN0JlVlpHWk1sMnBGQVZpZ0kKLS0tIGloYUU5NjltRkV3bERENGlNYzMv
            ZFROOXVUL01jbDg1V2FiWm9ZNGRLaTgKTC6RAuIdNes0uhUYJ36oQmX+YpXasbk8
            WaFaBd3wN2yDwoo/Jn4WB0TLdcrQtFH4MEee9uxcr7QI2jtMPAJ9PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    lastmodified: "2026-06-10T08:06:08Z"
    mac: ENC[AES256_GCM,data:U2Dkv5og5lq8EpHr+4IQOyXCvhPB0Jtjck1duW/stxvhil9/Mrsfdf0ofSexShZsfkZbtlkNVxldlxcDB+Hg8qgc+ggb9C1udPheKrJCaQA37DB9OC7+IPc/fyvw5HC0IHTgumtp2DJMOfAyShrOf8fZEdFk10SB7c6a3IDUlo4=,iv:hUaHyV29oaLzVj172KsBvuEjwKgKfOHc9Q3Qf/wedSg=,tag:u99SdZjXmPcNuol3d7+hbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNU9QNEk0dkhDd2ZCemJT
            UkRlZStvUkd1QUJxUWFmdjU3MXR3emxDWDBrClU4NVQ0SVlCOC9neERGYnd1azZp
            eHBnc2plN0JlVlpHWk1sMnBGQVZpZ0kKLS0tIGloYUU5NjltRkV3bERENGlNYzMv
            ZFROOXVUL01jbDg1V2FiWm9ZNGRLaTgKTC6RAuIdNes0uhUYJ36oQmX+YpXasbk8
            WaFaBd3wN2yDwoo/Jn4WB0TLdcrQtFH4MEee9uxcr7QI2jtMPAJ9PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    lastmodified: "2026-06-10T08:06:08Z"
    mac: ENC[AES256_GCM,data:U2Dkv5og5lq8EpHr+4IQOyXCvhPB0Jtjck1duW/stxvhil9/Mrsfdf0ofSexShZsfkZbtlkNVxldlxcDB+Hg8qgc+ggb9C1udPheKrJCaQA37DB9OC7+IPc/fyvw5HC0IHTgumtp2DJMOfAyShrOf8fZEdFk10SB7c6a3IDUlo4=,iv:hUaHyV29oaLzVj172KsBvuEjwKgKfOHc9Q3Qf/wedSg=,tag:u99SdZjXmPcNuol3d7+hbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
apiVersion: ENC[AES256_GCM,data:jd4=,iv:N2UOC5kaBFRk7ibPJHa+ARE04EsbnBLyN+VigijOEkI=,tag:b6JHIJWuHmF+DpWRJ45nCQ==,type:str]
kind: ENC[AES256_GCM,data:n0H56EeW,iv:8FjiY/JWIOLUqPtGzleeTuYmEN+z+JH6eP+c2yQTxIY=,tag:khyU9xevYzuKa+Wq+nrKzw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kDKDV6SllF4hMLXUO13JzUbXqA==,iv:jASzbfQGARD+Vfzro9xjDotCbo5ZPQLiieAoHsz7t38=,tag:+/zcSGk7O5pZdU0g+R66ww==,type:str]
    namespace: ENC[AES256_GCM,data:7XLQn1cC,iv:HcOchHaOjIAEvqOlv1E1iET1GYC90BgoDBR9G4G2mZQ=,tag:lBwFGmCnFvACF9vbd6hRRA==,type:str]
type: ENC[AES256_GCM,data:3TCp084U,iv:43dIAIArrMMIFP+PGk5dzb1tGSc+yu5zYiQSVFktXKc=,tag:avvv9TgYrUjPsmQNplZ+xg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:pjNVYXO6EEj7wmEKzSrSrsXnUNTheUT+D1JYFNXBrML7HXrt0STy2oJxbyOgWXwUAVtk0NQbTLUKQ5krqdZE/A==,iv:8kTnHrB3Nz1eSBmrv7GkyZajHJfseHanKgZXWZQxtM4=,tag:6GghkAYYzjjnQhl/LCNr/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNU9QNEk0dkhDd2ZCemJT
            UkRlZStvUkd1QUJxUWFmdjU3MXR3emxDWDBrClU4NVQ0SVlCOC9neERGYnd1azZp
            eHBnc2plN0JlVlpHWk1sMnBGQVZpZ0kKLS0tIGloYUU5NjltRkV3bERENGlNYzMv
            ZFROOXVUL01jbDg1V2FiWm9ZNGRLaTgKTC6RAuIdNes0uhUYJ36oQmX+YpXasbk8
            WaFaBd3wN2yDwoo/Jn4WB0TLdcrQtFH4MEee9uxcr7QI2jtMPAJ9PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    lastmodified: "2026-06-10T08:06:08Z"
    mac: ENC[AES256_GCM,data:U2Dkv5og5lq8EpHr+4IQOyXCvhPB0Jtjck1duW/stxvhil9/Mrsfdf0ofSexShZsfkZbtlkNVxldlxcDB+Hg8qgc+ggb9C1udPheKrJCaQA37DB9OC7+IPc/fyvw5HC0IHTgumtp2DJMOfAyShrOf8fZEdFk10SB7c6a3IDUlo4=,iv:hUaHyV29oaLzVj172KsBvuEjwKgKfOHc9Q3Qf/wedSg=,tag:u99SdZjXmPcNuol3d7+hbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNU9QNEk0dkhDd2ZCemJT
            UkRlZStvUkd1QUJxUWFmdjU3MXR3emxDWDBrClU4NVQ0SVlCOC9neERGYnd1azZp
            eHBnc2plN0JlVlpHWk1sMnBGQVZpZ0kKLS0tIGloYUU5NjltRkV3bERENGlNYzMv
            ZFROOXVUL01jbDg1V2FiWm9ZNGRLaTgKTC6RAuIdNes0uhUYJ36oQmX+YpXasbk8
            WaFaBd3wN2yDwoo/Jn4WB0TLdcrQtFH4MEee9uxcr7QI2jtMPAJ9PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    lastmodified: "2026-06-10T08:06:08Z"
    mac: ENC[AES256_GCM,data:U2Dkv5og5lq8EpHr+4IQOyXCvhPB0Jtjck1duW/stxvhil9/Mrsfdf0ofSexShZsfkZbtlkNVxldlxcDB+Hg8qgc+ggb9C1udPheKrJCaQA37DB9OC7+IPc/fyvw5HC0IHTgumtp2DJMOfAyShrOf8fZEdFk10SB7c6a3IDUlo4=,iv:hUaHyV29oaLzVj172KsBvuEjwKgKfOHc9Q3Qf/wedSg=,tag:u99SdZjXmPcNuol3d7+hbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
apiVersion: ENC[AES256_GCM,data:P8c=,iv:To86BLaJtCUptGmItahzmOjp3HvvGMZf1d5/9or1TPg=,tag:ApFPAjV5LvegF87bmpseqA==,type:str]
kind: ENC[AES256_GCM,data:6tvwR58p,iv:t9ebML2LlT+DtFUsVLOPoqNp1Gu2/qpHDneQ+zFwi3s=,tag:XXcTrBPRW5NVHb/9wK0yGA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:P0smZrwGjEbSqrdrIcejbWCKPA==,iv:KPacxd8WCAW8NSeANjTpv5wZhcV7OgkJqsTmyisOumg=,tag:JqCCRKFT0SqxUnpSkzdBiA==,type:str]
    namespace: ENC[AES256_GCM,data:PM3uzKAa,iv:kNFeP19mdz9n2+a1y26rMD8D+0UAfLFZZ0y2FfrsD+g=,tag:OYU/TsGbLbVzrjEvQJGyRA==,type:str]
type: ENC[AES256_GCM,data:TG8sV+NM,iv:owjdGEZTfzjnGdo0hrHv6sADskC9NfHu1Igo0JJ/bHs=,tag:tkO6+OcvXl7BklhxQ+bgJg==,type:str]
stringData:
    API_KEY: ENC[AES256_GCM,data:IPHs1iLfB42XHIW+qMJS2hK+FAnlpzK/EP5fDYMKCbq6m2ZVwVrUlNcMLg==,iv:emJTLDr50eATWBptHUogS9hwiTJRjAoMylWvQbHhptc=,tag:/EfcR64GoeBi1xoR3sdDwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNU9QNEk0dkhDd2ZCemJT
            UkRlZStvUkd1QUJxUWFmdjU3MXR3emxDWDBrClU4NVQ0SVlCOC9neERGYnd1azZp
            eHBnc2plN0JlVlpHWk1sMnBGQVZpZ0kKLS0tIGloYUU5NjltRkV3bERENGlNYzMv
            ZFROOXVUL01jbDg1V2FiWm9ZNGRLaTgKTC6RAuIdNes0uhUYJ36oQmX+YpXasbk8
            WaFaBd3wN2yDwoo/Jn4WB0TLdcrQtFH4MEee9uxcr7QI2jtMPAJ9PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    lastmodified: "2026-06-10T08:06:08Z"
    mac: ENC[AES256_GCM,data:U2Dkv5og5lq8EpHr+4IQOyXCvhPB0Jtjck1duW/stxvhil9/Mrsfdf0ofSexShZsfkZbtlkNVxldlxcDB+Hg8qgc+ggb9C1udPheKrJCaQA37DB9OC7+IPc/fyvw5HC0IHTgumtp2DJMOfAyShrOf8fZEdFk10SB7c6a3IDUlo4=,iv:hUaHyV29oaLzVj172KsBvuEjwKgKfOHc9Q3Qf/wedSg=,tag:u99SdZjXmPcNuol3d7+hbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNU9QNEk0dkhDd2ZCemJT
            UkRlZStvUkd1QUJxUWFmdjU3MXR3emxDWDBrClU4NVQ0SVlCOC9neERGYnd1azZp
            eHBnc2plN0JlVlpHWk1sMnBGQVZpZ0kKLS0tIGloYUU5NjltRkV3bERENGlNYzMv
            ZFROOXVUL01jbDg1V2FiWm9ZNGRLaTgKTC6RAuIdNes0uhUYJ36oQmX+YpXasbk8
            WaFaBd3wN2yDwoo/Jn4WB0TLdcrQtFH4MEee9uxcr7QI2jtMPAJ9PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    lastmodified: "2026-06-10T08:06:08Z"
    mac: ENC[AES256_GCM,data:U2Dkv5og5lq8EpHr+4IQOyXCvhPB0Jtjck1duW/stxvhil9/Mrsfdf0ofSexShZsfkZbtlkNVxldlxcDB+Hg8qgc+ggb9C1udPheKrJCaQA37DB9OC7+IPc/fyvw5HC0IHTgumtp2DJMOfAyShrOf8fZEdFk10SB7c6a3IDUlo4=,iv:hUaHyV29oaLzVj172KsBvuEjwKgKfOHc9Q3Qf/wedSg=,tag:u99SdZjXmPcNuol3d7+hbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
---
apiVersion: ENC[AES256_GCM,data:3/Y=,iv:KVStbn93n4V1lE4HNOAT2nqWy4VM0cB2hXOZQytJilU=,tag:T9K0jJJakGRiRcRQ9gQjCw==,type:str]
kind: ENC[AES256_GCM,data:HFDEb8FM,iv:3FROgDRX10omr3JjV1iQIn1jeE/UwB1zFwDWBqn7Zo0=,tag:xVvPfgt1DzHdaI5Li6aqhw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/k1NcVWisj2XhQHM7Zo=,iv:xA9Rcd7LLk4wHMQTLDWq8JiYXEv3QHvFSYXN5K3sK/U=,tag:no2D+dGDdsdoeXKaGVgY9Q==,type:str]
    namespace: ENC[AES256_GCM,data:0r0nBkucZw==,iv:8+/lOfo7VJZSSajNpxC2oP+PcurpDNebz33saKzTkYo=,tag:MEJgvW0pi8lXEEKCMhSGOw==,type:str]
type: ENC[AES256_GCM,data:2TiyGzs2,iv:c+ylm4vU+pO5x8/YR3pKzZsm7/FtAxnqnJvzOrMRZmY=,tag:LxLxVxTw8EqLeraWkLTVIA==,type:str]
stringData:
    TUWUNEL_REGISTRATION_TOKEN: ENC[AES256_GCM,data:Kupi1a7wYwkVmN3UUtHkYQzrJk4Iq1u5UvF24qAeyOln2VcIksqAe3vzl1j0zDKt1Q/Tt37sbvQ5Li44p8jv8Q==,iv:Qqro06XAriMK7hSs26BQ/FcKf9k2wC3j2ugCQZbLtpI=,tag:cpmOgB2d5FJ68Bs1wr1YOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNU9QNEk0dkhDd2ZCemJT
            UkRlZStvUkd1QUJxUWFmdjU3MXR3emxDWDBrClU4NVQ0SVlCOC9neERGYnd1azZp
            eHBnc2plN0JlVlpHWk1sMnBGQVZpZ0kKLS0tIGloYUU5NjltRkV3bERENGlNYzMv
            ZFROOXVUL01jbDg1V2FiWm9ZNGRLaTgKTC6RAuIdNes0uhUYJ36oQmX+YpXasbk8
            WaFaBd3wN2yDwoo/Jn4WB0TLdcrQtFH4MEee9uxcr7QI2jtMPAJ9PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    lastmodified: "2026-06-10T08:06:08Z"
    mac: ENC[AES256_GCM,data:U2Dkv5og5lq8EpHr+4IQOyXCvhPB0Jtjck1duW/stxvhil9/Mrsfdf0ofSexShZsfkZbtlkNVxldlxcDB+Hg8qgc+ggb9C1udPheKrJCaQA37DB9OC7+IPc/fyvw5HC0IHTgumtp2DJMOfAyShrOf8fZEdFk10SB7c6a3IDUlo4=,iv:hUaHyV29oaLzVj172KsBvuEjwKgKfOHc9Q3Qf/wedSg=,tag:u99SdZjXmPcNuol3d7+hbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
