apiVersion: v1
kind: Secret
metadata:
    name: immich-db-secret
    namespace: immich
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:5mWBqe66bGASTHfSXhcG84gfy7mb690uH1PjtjtrRlIKpCW0piAdjo7LQXAHCG7uUoCiEnphyIktWQeyErboOA==,iv:I3uoEk4coosh/DPTiJg1KGkijjnMJ8hWluJD1OucBWs=,tag:/SKCqby/c6AcBXwYfViR/Q==,type:str]
    password: ENC[AES256_GCM,data:xf8h2D1JI237rySEkD6Sdsm0hVw3ZaT+iKMUo15TUr3vPshjUfVsDfj7WuSYClbQK6xf6/DdlS7kQjfVoaZ9/w==,iv:x9oqr6Siakeyn5o0oxQR2g05C7K8nJoWUyHFMTl2Nsc=,tag:yFxtnJMebKhI1husWUMWhA==,type:str]
    replication-password: ENC[AES256_GCM,data:71Y6RhkJyVZAgug+fVZhHy7CvXVidNN/xYSYb81nGSF5MyX85uY7c02zSeQY4o608UPvitqNiJvfSLb+qY+6Hg==,iv:ByaDZmbmRoGM6ccwyBzr4Re6RMH9CaK/48S3ovao2DM=,tag:WDmd9NZ4ftz01sASsgmomg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTFd4VmYxWW0yeVVRelZ5
            czdGcCtzWXB5S3BxNDRMUHRtU1NmakJOMTFrCjRNa0FLVHh4Sk5QWC9ZYlpSMlJw
            c1B1TTE2c1I1VDhtaGRkTDlWTmZ2U28KLS0tIDVraU1FMEtrVU8yTkxUN0svNGxn
            dDdMTzF6dzVTSDZ3V09Vc1Fmb09Fcm8KId0gRE/7zEVs7ZFS0GBCfyupSg+N7w1v
            dEWml7bawzi+qNRE+P5KPDCDCh/camcQ+lC2eDh+hBdi+EZAQaoqoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T04:12:56Z"
    mac: ENC[AES256_GCM,data:8mEIA7VRhpDwHJAnE7D1CDmlvlUmqdKwvWmDyTGjAItwWQsizMqUn06zbMEjWDrSvNGNYUFAJeOOW/J1QnSmoJNcdLtYt472ajyFpAISHVfBwoqx9tVK/smW0RB8dhc1yz/hO7FKcqNJfjknfezTQDI+xspY8GVElCYEVQJ0RLo=,iv:djGX2DLmKs8QyRMpGrcz58M4r4XY6Y1bGrWGxZW2LGk=,tag:Ci/++HN5fTB2QVs2HGsVcw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-redis-secret
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:2bLGTMvHyeagzwSICiYHzHZ32hHp0LLBxcrttg1t+oq0utXt95JJ+MGtIOQtUzPZcPpifnaemjcqamZa9iGFqg==,iv:AOrvvEqtfMfuA3FqO2BcrfnmHxKX/Zu11FvpqBUdtPQ=,tag:j1wkqJVo5vNdgivLIMDXXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTFd4VmYxWW0yeVVRelZ5
            czdGcCtzWXB5S3BxNDRMUHRtU1NmakJOMTFrCjRNa0FLVHh4Sk5QWC9ZYlpSMlJw
            c1B1TTE2c1I1VDhtaGRkTDlWTmZ2U28KLS0tIDVraU1FMEtrVU8yTkxUN0svNGxn
            dDdMTzF6dzVTSDZ3V09Vc1Fmb09Fcm8KId0gRE/7zEVs7ZFS0GBCfyupSg+N7w1v
            dEWml7bawzi+qNRE+P5KPDCDCh/camcQ+lC2eDh+hBdi+EZAQaoqoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T04:12:56Z"
    mac: ENC[AES256_GCM,data:8mEIA7VRhpDwHJAnE7D1CDmlvlUmqdKwvWmDyTGjAItwWQsizMqUn06zbMEjWDrSvNGNYUFAJeOOW/J1QnSmoJNcdLtYt472ajyFpAISHVfBwoqx9tVK/smW0RB8dhc1yz/hO7FKcqNJfjknfezTQDI+xspY8GVElCYEVQJ0RLo=,iv:djGX2DLmKs8QyRMpGrcz58M4r4XY6Y1bGrWGxZW2LGk=,tag:Ci/++HN5fTB2QVs2HGsVcw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: tuwunel-secret
    namespace: tuwunel
type: Opaque
stringData:
    TUWUNEL_REGISTRATION_TOKEN: ENC[AES256_GCM,data:rG5IxOTt3w/eCqLfg9Oux/pR5I+5FQqH1vl9SgmOFt2A3BcrOO1SnL/3bbzvyYYETDhPXfdE0HUAj5/4L1V8yA==,iv:dr333DFB7+6J48d+5LhRsoCZFOmR5LfwlznmDDwxUR4=,tag:0HhnJ5EoIsjUgRBXFYzD5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTFd4VmYxWW0yeVVRelZ5
            czdGcCtzWXB5S3BxNDRMUHRtU1NmakJOMTFrCjRNa0FLVHh4Sk5QWC9ZYlpSMlJw
            c1B1TTE2c1I1VDhtaGRkTDlWTmZ2U28KLS0tIDVraU1FMEtrVU8yTkxUN0svNGxn
            dDdMTzF6dzVTSDZ3V09Vc1Fmb09Fcm8KId0gRE/7zEVs7ZFS0GBCfyupSg+N7w1v
            dEWml7bawzi+qNRE+P5KPDCDCh/camcQ+lC2eDh+hBdi+EZAQaoqoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T04:12:56Z"
    mac: ENC[AES256_GCM,data:8mEIA7VRhpDwHJAnE7D1CDmlvlUmqdKwvWmDyTGjAItwWQsizMqUn06zbMEjWDrSvNGNYUFAJeOOW/J1QnSmoJNcdLtYt472ajyFpAISHVfBwoqx9tVK/smW0RB8dhc1yz/hO7FKcqNJfjknfezTQDI+xspY8GVElCYEVQJ0RLo=,iv:djGX2DLmKs8QyRMpGrcz58M4r4XY6Y1bGrWGxZW2LGk=,tag:Ci/++HN5fTB2QVs2HGsVcw==,type:str]
    version: 3.13.1
