apiVersion: v1
kind: Secret
metadata:
    name: plarza-ghcr
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:cybJEVymOD3wAoyz3Nbrc62peZQJiClVOEFZ5kbUfzU7dG1hwVsto1LGyspI4jcULjd5VM82D9N7b1TRDu030azZP1+2xr2QPCOg6Wz7N+R9QHjdeV9yWzqzF8jCBFji/hYOmcx91InVJdvacPWauYwGMLyURnL1mIoFiZa13xrutWcPDhZcD2DSUwHyPwSaIPIXBap9QcxupeINQ0w2h+a2g6IjXnYDP2618Q9lWyfyKkfUwmFlNZae9Qk/jqJ6gHndvk+Fz/352ddkvbRBpsPvK2Jgh3rDUNs+9+K0d2DBWVWD,iv:y99+jqZmwY9t07uqcX0+J4c39siaEaL3zIJOUVS7Ftg=,tag:D3WNTVzm/BTCLS7LsMOQPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWkhxckk3aTM2akVJdkJ5
            MjkwZndtWWR2RTN6LzkwdHhJWlVYNnJzaUU0CjVwL3AxV3FnSXZNT3JnWnB6YVdQ
            TGpWMWVuMS9wZXQ0SXhKQ2dOaG5pWUkKLS0tIFRuRlNsSVlRaUNDVlRTSWhEdWN2
            N09EWlFJS1NORllWbzMxenBHZU1yVzAKTL4kiYYpsKkRyUjhS/t1Pe3GIktsEhXX
            LFk56xvLaI/o1f2+6uTE8NhH7f5PPhCh3hOxNUmrw5YyVjrVa2LZLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgnp0qs4w0yyy6r8shpjea6tepyygdj4xr2wvx8dkg9af7te648s9drfsm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T04:08:43Z"
    mac: ENC[AES256_GCM,data:VSwwP2v2uWL84DhNBUozoGE/rRfAecXvW+DMbVWOVmpihnb6eiNDz4SJMuVW+L1QirBu7WLbSIMkassNSW30v0CNmCQw8R/EeeERe1hiwlhCtn4YPM6s/R8RqzLIvbK6NDHhgWz5mqSGzduoAXmoiaIWE6g7cInMgkzedyoe5wQ=,iv:yaMqQiWDBD6VEJt1lyAUeJsMkOYCVYEW5mAx7ij7ef0=,tag:aS1C2GQlM42HcZYsFSUpGA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: plarza-ghcr
    namespace: plarza
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:BzqaDp0T4iSpMYYRlynTJUIplIkUXOZ9v/QmTVqMQkACz/Kdb5rFL9QS1zbu6JczjYGin5LVqWrArbK+U7xy1iBhhT3SdbeDh4Aejfql/fKKqi9nR5gu+uhmNoPW3/ydgWUwLc9v0LkHolP3/vmZLy3oNHgA/5ZYX8guTycBS1FiZA0s5H4/b4srtBvV0amQz8z6RJN109WPzbVsgBOuYDCHXpqa1F8KnQCkxo2/KCiWIPYNqiS23iPeU8Obrm7q6JkYNRgMarOiAvbclzXr/kSPlQK+X/j9UjF11ZX+uZGV82BN,iv:qySofRUMPmjZVG3UpvIlUJt38amCLix+rfz6a5634hw=,tag:iavfuDwaPcJIFZbsMLWcgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWkhxckk3aTM2akVJdkJ5
            MjkwZndtWWR2RTN6LzkwdHhJWlVYNnJzaUU0CjVwL3AxV3FnSXZNT3JnWnB6YVdQ
            TGpWMWVuMS9wZXQ0SXhKQ2dOaG5pWUkKLS0tIFRuRlNsSVlRaUNDVlRTSWhEdWN2
            N09EWlFJS1NORllWbzMxenBHZU1yVzAKTL4kiYYpsKkRyUjhS/t1Pe3GIktsEhXX
            LFk56xvLaI/o1f2+6uTE8NhH7f5PPhCh3hOxNUmrw5YyVjrVa2LZLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgnp0qs4w0yyy6r8shpjea6tepyygdj4xr2wvx8dkg9af7te648s9drfsm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T04:08:43Z"
    mac: ENC[AES256_GCM,data:VSwwP2v2uWL84DhNBUozoGE/rRfAecXvW+DMbVWOVmpihnb6eiNDz4SJMuVW+L1QirBu7WLbSIMkassNSW30v0CNmCQw8R/EeeERe1hiwlhCtn4YPM6s/R8RqzLIvbK6NDHhgWz5mqSGzduoAXmoiaIWE6g7cInMgkzedyoe5wQ=,iv:yaMqQiWDBD6VEJt1lyAUeJsMkOYCVYEW5mAx7ij7ef0=,tag:aS1C2GQlM42HcZYsFSUpGA==,type:str]
    version: 3.13.1
