apiVersion: v1
kind: Secret
metadata:
    name: plarza-ghcr
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:GIZ4+Vz1922W4T0HVJ96kaooG+feDb0Xe6VBws1fX5jQA/fOQBiAiqvB4xTcXlf5vAdcrDBXMGIX4xmYXkHzhimH5wM1bzdWyL3v7pkk6aNldTT0uYeUAQkA3lQvtVo5eFY97I3INnOqoLRHBe853cRmBZWdGZrD+mOUy3ChBnhVThDNK1u1sbcFIpG2f6Lf4hRGEzGRO0FwezjKvxflTVmiD5vI9jBT2x9IxYPzDWFI+HY22f5kJO3Ljq8vlBq5Q32MsrrKfE8GTQqRxQyh79sOsMd348amYDGFmuNAQVNCpqCY,iv:2PQnFVhkhOV6o2MgDHy9FdWDkGkrty1kZmfO7bHfp1w=,tag:DJCzpNS1tOSJkKmPeW8U4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMGQzRFk4UkNXN1BMUmpq
            NVVpYzdkRExOUndSSHlCOFJOZi9RWVF6T3pFCnBlWW4wNS8wOWEzbzZaL2VRMHpV
            RVJQOGVQOEtSYlNRc0ZmUGREMW5FVzgKLS0tIGwxUFhjL243MXdJaWdCQVNnYitO
            bWxRc0t6Y3VueENCTHlPOFBGcnJoMU0K0SMpTB346KKSnob58+LGc+/3JC2Se6gU
            923y1UUWEYlYmYrRlDYDHo7ydj7oqVrFD+5ur+9H8i27pFRf6orWsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T04:13:07Z"
    mac: ENC[AES256_GCM,data://UGPhG7YYCahmrYCeax4VCKigWFi2XK+mhnXPobfgN+BF+flWZ0+PhZVj70CkicyKXjnN48GWRdkywneFMEdF+1C5WOekPjhxZfj9ssDRownz2fV+GmtwGBxRH71JeIaa8VYVYqThPT8SiPi5hQ7NNwPlWQuSRdKerKSyktC8o=,iv:N0ffPFkdEpQ9RkXZEUjQNWalS2h+Ic2hAAENSlzV8P0=,tag:RP1zBnspLuHxGw+otE/ogg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: plarza-ghcr
    namespace: plarza
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:ENi6uduQdn1ON5Ye13D4oNnvF8lTss+U2J9L1BJ47zh7yblt127LBCeVr/mTe4yaoJIKb6j8tdDq8O1lXpD3PuKmpQ4Xt5iw2iGrJuYwNzHYTraaPGQejPwD6PGEcHaxjaDQ9h7D1S43CgezN1KBYLyw+rO+tU2A+ZvMrNdprJdGTgeu1ZuUouPkalvJ3CfzYaRbEsjmEDBI7SHYZsWvEbpwVe0GtIkZ6n9sb56ZoPNme+qXlhgpNja1qFS9sRFW9E48F4w6/K2UpubQx3H8Bu/ftlBDY8GFcv/FY3tW7Z5GFSR4,iv:4FZLwUWHHiVoQTkF/oo2Av8ig4taKSVm6F158ZuCZoM=,tag:6yQsdYxfahTqj44aJbJ32A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMGQzRFk4UkNXN1BMUmpq
            NVVpYzdkRExOUndSSHlCOFJOZi9RWVF6T3pFCnBlWW4wNS8wOWEzbzZaL2VRMHpV
            RVJQOGVQOEtSYlNRc0ZmUGREMW5FVzgKLS0tIGwxUFhjL243MXdJaWdCQVNnYitO
            bWxRc0t6Y3VueENCTHlPOFBGcnJoMU0K0SMpTB346KKSnob58+LGc+/3JC2Se6gU
            923y1UUWEYlYmYrRlDYDHo7ydj7oqVrFD+5ur+9H8i27pFRf6orWsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T04:13:07Z"
    mac: ENC[AES256_GCM,data://UGPhG7YYCahmrYCeax4VCKigWFi2XK+mhnXPobfgN+BF+flWZ0+PhZVj70CkicyKXjnN48GWRdkywneFMEdF+1C5WOekPjhxZfj9ssDRownz2fV+GmtwGBxRH71JeIaa8VYVYqThPT8SiPi5hQ7NNwPlWQuSRdKerKSyktC8o=,iv:N0ffPFkdEpQ9RkXZEUjQNWalS2h+Ic2hAAENSlzV8P0=,tag:RP1zBnspLuHxGw+otE/ogg==,type:str]
    version: 3.13.1
