apiVersion: ENC[AES256_GCM,data:5Lo=,iv:zPHvZXX/q9r6UsxXS57C7TlxmHgOiTZjpZKzh4xX3gs=,tag:mOVQQwOBA2SH8yHEf85cBA==,type:str]
kind: ENC[AES256_GCM,data:CKVzBK7b,iv:xKxuDtICFGLVnUu6659+blMdJmNNY8EROHrwhk29aww=,tag:7D1dPSzHt0KsV5XQnb3LTQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RRSAROqxsWGojg==,iv:36FIpPn14im2rDe/inPka22F35YyvBhmx0o0apzAy9M=,tag:FAhAuv4WfAZmjGC/JO73Og==,type:str]
    namespace: ENC[AES256_GCM,data:PzgPIuim,iv:cEs6ajCNR+YHorxkSZlJsKHpU9WePZA4M0cTfh615gA=,tag:UqjqvGH4mIURPteXL2Q8jg==,type:str]
type: ENC[AES256_GCM,data:H9fC+SKm,iv:+xiEKUOXNVSKnRMMoDS8X337v+FEXOLVSOmIdZnusCk=,tag:sTny168c1BSCwhYh+gYI0w==,type:str]
stringData:
    AUTH_EMAIL_FROM: ENC[AES256_GCM,data:+918SBVr1i3eUVB+xdcUoBDAJ/GwGw==,iv:Wa5IWLu5+Jib31ctZXcofNaxZg15DT0ZaqZL6HRSpYQ=,tag:gGWJWcBV9pyNgCBWUc9eeQ==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:TlCOunnAuxybCpbptlXW/xQDrb8pFy7cuFN9iowkFWG+7cCvqNwZESR19OiT05LPA8pSXqj3ou01Ij9HsiEHWQ==,iv:n45jCus5C7TsqySW3ToMttVC4qPXt0FHGBshgVzysXg=,tag:aCsX4aux+oSNSNtJ6faANg==,type:str]
    BETTER_AUTH_URL: ENC[AES256_GCM,data:M8OTmK4H0osBQGx+ZALMG44I,iv:8s0SIDXwXoXoTJTf2ssFnNLwyHlTNUH6PTVdBmeNIOc=,tag:Y6rf6qQOkdCJWYzhtyFv4Q==,type:str]
    BUNNY_PASSWORD: ENC[AES256_GCM,data:kHgrMHSK90M6N+nFpT1TVHuh+Yw61UA1986sCq5WRYIr2GdqhfGX9+A=,iv:NT2bL/i0OOMlBxktIanAmKH608E5NFpoOi2R7SSklw0=,tag:WFQwrhTOUr0RQcU+uSx7UA==,type:str]
    BUNNY_STORAGE_URL: ENC[AES256_GCM,data:srgMZc4G/v835BxkOcAIaQ1+7fMvDc3ElCI+zMtkyNNbBKKgRjbB,iv:tb7wFk3owWzI3bVAXJFYa2YwBO/3OYzXIs7Cl3DOzUQ=,tag:P0TwJEVqZL2Amhcl7oBMxg==,type:str]
    DATABASE_AUTH_TOKEN: ENC[AES256_GCM,data:xCNagIdM6cs8yodex8jtawpyvwXeLpIeW0NoZSP2zV8Z80wPe7QeYBHiQZ7MNzhXSt+XsqiLafFKyHfx3YLVIRVeVfB9NO2yXxzqgXli2Js/JY64/wlJhhf52vArk6F5DX8/pu0ZB1j0S3xdAz7AE+wdtBuddWoQlDuCCVKHtw==,iv:Lk5lK/OTheB1eEnBCeHC9TW4GE7UvLYKcOOTMIPikBU=,tag:q2Rz613AOG/bYpEO7tikOg==,type:str]
    BUNNY_URL: ENC[AES256_GCM,data:laaZiVa0g0CmTCTQRSeWpp0zyMkQig==,iv:D91PH+Teg0D73ZgptYb+UN9aOonlpba1zCN+ACC04xU=,tag:LNbcxbMSiXzw46gMcOWltQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:YttEKu3eRWLlhgMfz20Jd9W0gLqs3zTt0fmRra8GLYYQo7NiwoHyzXtpkQH3tXNulNE=,iv:Hmfq87x/cbZemD8rA8ILuI8BccofzvgnjuCmvDGdLMU=,tag:Is5COqqv0er3EN/4x0MnQw==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:e3+YcaL8CPkfgKCq2qdGfboHkE1ces7REweekuHZ4x2Mey/Y4Rog++UWGUid8RCiVIxl34q6zKhpPb6ArrnYz5P8mwTlmBU=,iv:/XIbP2DEnESHIn9TihxIiFkNqbSd+ESluZ0uEZD8Vk4=,tag:v0reSHKzpS5ZE4KhuNjSjQ==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:QoSzEcV34/mgYshtCSJTukQ7fSHqL3K+M6thwi113tWgT34=,iv:18CsIRahLhIgiIH7+9puVYD4sVG0c3neAI1Fh5Wf75I=,tag:aw2xHg+1eykmjSOjJAAKbg==,type:str]
    JINA_API_KEY: ENC[AES256_GCM,data:lm8fIK0xIAuKckoQibIS1UX5psWqY6wrizi1K90O2aVRdAJOADMY2ra3ANglAh32BbyUZDgDbLL4NjphT8aWoq4=,iv:QhOU8TlZ8KX1X8fQc+7vFTsc5jjUVdD/kpSG2prZlpg=,tag:CiDfUXKBHzUhrRQPM1opbg==,type:str]
    KLIPY_API_KEY: ENC[AES256_GCM,data:oz8V0eOe82pTtLZfPlZkDul0RNXMbNV+EE8cgwfaKxmfbIlAIkR/2IR7kid5cNXtpoNvNx5sMNDcXkeFUcv8gQ==,iv:4FRH+SKVmYXczvXtTQL0NNPYQ+7N+T9bvXY+VBQs03M=,tag:7CyLJbJ6GQ/VHy2oO/Bawg==,type:str]
    POLAR_ACCESS_TOKEN: ENC[AES256_GCM,data:4c7ywDwngi8yZLFHPH3Ut6SjgGKbiXib56NxKnx/3/iF2a7PZLcbR37nwHBxdT324k64ZKA=,iv:ZlHZg8kqC5BidtZGmFAjSI57EWSEu1iCoEUHoOLVKVs=,tag:4oRGwageCRf53cJs4dJLwg==,type:str]
    POLAR_PLUS_MONTHLY_PRODUCT_ID: ENC[AES256_GCM,data:3Vw3UHIAF6oJMG69rj5ObsJqPVpQLH5/eDornW5sT1puN1ju,iv:m3t3EUi3QCmbtVPANaEYX38PfYD6tH0Fz64thPpLJ9k=,tag:dF7K9OyGPd4SFYhnHLuaqw==,type:str]
    POLAR_PLUS_YEARLY_PRODUCT_ID: ENC[AES256_GCM,data:kxVxDZjVVeRph8PKJYZfhkO+OT8zBFIgBvNG+XnT12cD+LRb,iv:Hvpd5N1YGd0tNulHWgJV2ZZZ0a/yR7U+hYBsrASE8Ks=,tag:P7FDqTUyUeEjBhqUssC1Lg==,type:str]
    POLAR_SERVER: ENC[AES256_GCM,data:nuT0oshFjoOfog==,iv:lqMZVn27vCoul40pzSoOmzTSV2x1loPB7+utoMwwaJ0=,tag:rlj0uEBW8yQF1cxdSvcVXQ==,type:str]
    POLAR_WEBHOOK_SECRET: ENC[AES256_GCM,data:Cc53AIJJiMh8y1mp/P4IRstwsTXFZGUZiXgmHCOjrfHPQsUcbMcxxPHQMF46mKEmfjGDAB0=,iv:Knm8Nwook9H0/cglQtn2BQLawXtZAUQEPSN1baoKYtQ=,tag:jNA4pAUf4vdCzi1FqwlL3A==,type:str]
    PUBLIC_POSTHOG_KEY: ENC[AES256_GCM,data:5PL2RbhyQ6OElmW8KTE2s+m8jSkt7AxchTnKsCiZT8mBGM1bcyjwgiflWGqVd5M=,iv:ruiaJsRazQolzfrOSByoozzsVqFy/HyhYUncs6DIuR0=,tag:R+KGGLD/e7TFle0ozlDoDw==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:fTzp4Zmq+w1aPp/4FCXwOxyi4/SsUVJE0l6GoKhjO3DEgc/N,iv:dBa+vEQOu0AoXcHsNllnNDpfwonMamZbM1E62W0ryjg=,tag:1sLe2vE/8wXsXsteof+mGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTnN1eDRiNmRxRU5sdXNx
            NFhDNnhXb3hmeDU1bzBHQi9NdUwzS2lXakYwClFHcUw1NVEvQlVwS1N1MnlTYk8r
            em9ldDZYTGEyd3c1dHoyZTJReDFRazAKLS0tIFhaeHUxKzkzM0V2Q0t5djRJQVBz
            WE9wOEs4M0RscWk3OGZ3WU5hSW1xMHMKma3dHbHzRGVASM5t1YIQ9a/NKvklh5xb
            TYZDMI81Syx7wACSjE95GjGevbRjDIMS/Uac7tcx+6C6DjjbVDueog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    lastmodified: "2026-07-15T09:32:43Z"
    mac: ENC[AES256_GCM,data:OoLPGaHg3aQJxMwRaZGSeI/RiEhN8Ec0NzBtYkLBEUJQh3x+fOrUtQUxwdZioxgAQPu/L+G0YrSaBA1dRuB9/JE5cmWeGx52Wl3kB2Tn/IrwSEcomnh9xcK+OHnKvxd9XAB5rRorJ/fSf6lNLkTrn8oozsEc5DyaIHRVmxxBHf0=,iv:INxVHJ1YjWXR06pQbgNfvF0lblGa1XnvOlo2nH2vS+E=,tag:X4+gnO4WVLCabFh48ocQ5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:5Lo=,iv:zPHvZXX/q9r6UsxXS57C7TlxmHgOiTZjpZKzh4xX3gs=,tag:mOVQQwOBA2SH8yHEf85cBA==,type:str]
kind: ENC[AES256_GCM,data:CKVzBK7b,iv:xKxuDtICFGLVnUu6659+blMdJmNNY8EROHrwhk29aww=,tag:7D1dPSzHt0KsV5XQnb3LTQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nBKD8lKg1HiKovKYNKhOReIs,iv:4A4oZ3PrXda6delYULEhmmnwGPxerTvhuTigq+SsTus=,tag:vylZRmv0boIV05wrsbXkUw==,type:str]
    namespace: ENC[AES256_GCM,data:PzgPIuim,iv:cEs6ajCNR+YHorxkSZlJsKHpU9WePZA4M0cTfh615gA=,tag:UqjqvGH4mIURPteXL2Q8jg==,type:str]
type: ENC[AES256_GCM,data:H9fC+SKm,iv:+xiEKUOXNVSKnRMMoDS8X337v+FEXOLVSOmIdZnusCk=,tag:sTny168c1BSCwhYh+gYI0w==,type:str]
stringData:
    SQLD_AUTH_JWT_KEY: ENC[AES256_GCM,data:2MNiGk0kMA25R0DT8BOYd0NJGQIRA8phcBxAw3zFpl/vegz4K7uhZ7fv6kkhoFfiaehJv8IMtg6bHCXbARoKZ8kn5xNupMn3u0yOU4BKl1CU4CQAKa7ALJc812NQmTGgLGCZpeoNIYE/gDTKUSgbMaQ=,iv:9kCcFbcwoX/gQFGg8xXtRCOhmecwlgYlNECH2aKiwyI=,tag:l4oTWsLu9OFp679tIb+WTg==,type:str]
    SQLD_AUTH_JWT_PRIVATE_KEY_PEM: ENC[AES256_GCM,data:tXSN8hH+DvVABdKB4XvLHa/B+rEOPc62qla/5BES9orec+yrPFxeNlLstl5wEKUN5A3P4qrr02DQtuHYhGXkCDZBH9fydWuD8a+duG9+ejUnQBIDRCxZ61/lRQiyAXCRa7ngGfd8htd+vn1itXuWu92zpKf/2Ew=,iv:6OB25rUfNkMm85pMfFdpNsYEme3pOgdCJnX1atbgTtc=,tag:mGjAXM56MrzK9o7tQuc2RQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTnN1eDRiNmRxRU5sdXNx
            NFhDNnhXb3hmeDU1bzBHQi9NdUwzS2lXakYwClFHcUw1NVEvQlVwS1N1MnlTYk8r
            em9ldDZYTGEyd3c1dHoyZTJReDFRazAKLS0tIFhaeHUxKzkzM0V2Q0t5djRJQVBz
            WE9wOEs4M0RscWk3OGZ3WU5hSW1xMHMKma3dHbHzRGVASM5t1YIQ9a/NKvklh5xb
            TYZDMI81Syx7wACSjE95GjGevbRjDIMS/Uac7tcx+6C6DjjbVDueog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    lastmodified: "2026-07-15T09:32:43Z"
    mac: ENC[AES256_GCM,data:OoLPGaHg3aQJxMwRaZGSeI/RiEhN8Ec0NzBtYkLBEUJQh3x+fOrUtQUxwdZioxgAQPu/L+G0YrSaBA1dRuB9/JE5cmWeGx52Wl3kB2Tn/IrwSEcomnh9xcK+OHnKvxd9XAB5rRorJ/fSf6lNLkTrn8oozsEc5DyaIHRVmxxBHf0=,iv:INxVHJ1YjWXR06pQbgNfvF0lblGa1XnvOlo2nH2vS+E=,tag:X4+gnO4WVLCabFh48ocQ5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
