apiVersion: v1
kind: Secret
metadata:
    name: plarza-app
    namespace: plarza
type: Opaque
stringData:
    AUTH_EMAIL_FROM: ENC[AES256_GCM,data:+Q2HsGMWwj2HxlSYq5kyByuxOfQwHA==,iv:ZI8wPXEtFCfyl1wXYI5N53uWqiPDn9aoEjvf92+rnIg=,tag:pHz8nkBJP+7otVh3gi+JJA==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:iP3Z/8FWxZV/9qLfJi2O2mLQ4SBTxmRs5kEMJGrHlhF4C5aQq100xNwOal6j4SlU1F6fbHosoAR4jonXgRPaBQ==,iv:U6h/1JoS/8e1gB7UXSpm77BBm5cpK+2vmd6Bh6B1TJ4=,tag:SdkNAiWNKBirDSo+Jn4/Bg==,type:str]
    BETTER_AUTH_URL: ENC[AES256_GCM,data:ZJ9IPwvTZP+kNBBDai5oIc0X,iv:1fp6jDA0Si/b4kDWV07CVHqmlzby/1/gTfYTR9a0m94=,tag:hnaIMCq2QYnCvfKzp792Rg==,type:str]
    BUNNY_PASSWORD: ENC[AES256_GCM,data:mMF5XdFfYpZu4hwUqo2cLCPTXZyYbsPwQuCuQkGmpOVTFW19xFHC4v8=,iv:DEfFS9le24Dh5odvESPH6CfKkhGEHTE2zO1sUrwcw4k=,tag:XyV4icRbWTFCIS4d9Kx1bA==,type:str]
    BUNNY_STORAGE_URL: ENC[AES256_GCM,data:rY49+3CatnNc5AyRT2qq2x8EbdM59cw4uUTxJeaSDDdkKacfOF6a,iv:4CIHHiJgSos+PKDK+W2x9bt4bY2ibDzVXdrIJgb6a3k=,tag:zMo3muzthigqHveu3iJdWw==,type:str]
    DATABASE_AUTH_TOKEN: ENC[AES256_GCM,data:qNrR5VfOAS2jCgPLPo0waJ8LXcGxfopxgvSyZCM/U9+JapDEEiFnSHaAdYzIG4lNcYuA+CFumGBzLzpnvLvDA94Q6G0pRQzZZ7n2msr9ckP7FvTB3aLgzeIwT4/cHSHC/5G4HuAr9iajT/FIRrBOIExQM08Sm4EBlsm6lgLc7g==,iv:RP0MReSrGMUNX4bBuIMtoYmfxrh0YicBewJ9FpZqieo=,tag:HGmNvq5+KSWan8CqsxiZgQ==,type:str]
    BUNNY_URL: ENC[AES256_GCM,data:3ir6EKNa4NV4+U6B2xLZk3dBQmb1MQ==,iv:snNU5KYs45Atc2se9P8qZ71k1+ExHAREPFiUchRPC3E=,tag:DUfn4FgCre39dJZ2ncYfIA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:JKulMfDZOxhZKX47eiX+4r1w/D+oB5y3mCjLgQjgiMVuG6RDixZHWS4x8GLGLCp+bvE=,iv:qBGL+bJvfN3xl9DL88W0WPkVnc0SGW+aaZCK3wUVAjg=,tag:bc0iv+Ly+uE3Nc/Iqycnzw==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:TKc988kcqrTPkR0sshzOavX9Stv0wXeM3rNj3b4+Ax7T1tKf+fRas3TpNoQx7N0Z9vqzFwljnM3JFJfGrEB+RBwGVGqcTwQ=,iv:QHTZdXEFdKwUqT8IeQuKhS9Z4VAwuhIOvbGR4xlVBYc=,tag:O7UX4VwKuJYJIOp/vCYOtw==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:zSPTue0p6+BEsFZzJ9kWia+AbsNUzcbv15Y/lgeZElhNxzo=,iv:BWdoVun9ndfi9cW1oJomwJ7jaRlknn+26CxGgh6e2LE=,tag:1dcRH3AU1BzF2Y6hR195Wg==,type:str]
    JINA_API_KEY: ENC[AES256_GCM,data:WP/yronXlf4wPz7MtIRxs6R6brB5+ADwEwInnBHVc0HzlNR7x6MehAYp88VOQ7NFkamHxGwVA33duly+e7k4dgY=,iv:afJcSPTls6X3X4BzF1fOqaNKQb+LBr/44EYwGzKhWhQ=,tag:jIrdgESv8oMtQ794TE69Yw==,type:str]
    KLIPY_API_KEY: ENC[AES256_GCM,data:MSvlTLPUG+RrYuMdEcJPGDPqDjwOMU3f5+SnlqeHIhJ7cULQrUB0aPUmTc96s6T05x/H+AV6YEc6N3lsCQRAOg==,iv:EOEcktTFXoz7hwKeOYZCZSatEbGVGv0e7c9Djnq7fmk=,tag:lWlw9OMtViHyfvWEcD59bg==,type:str]
    POLAR_ACCESS_TOKEN: ENC[AES256_GCM,data:cDmdnWJzC8+Ryh0JRWCjVObgYe77Vnjq2k+5JcUR+cGuYMOx1aLYtgTgtD7arg0b/LsnGP4=,iv:QalCp0uXvzHkEUEuOW0ZXO9msoNmG2GZjCpDjzYoS6w=,tag:qy+3t232vA2tB3ivXQAadw==,type:str]
    POLAR_PLUS_MONTHLY_PRODUCT_ID: ENC[AES256_GCM,data:3Xxctg5Rh7X+kJKuMmlQcn+P0U5qxCRMX+1auvP9uB+LfPtC,iv:+teSL15unrryVsVyo62EciBKofMnWf93iyXGEgTSFC4=,tag:uTZD1dmRSg195dfR5dRP0w==,type:str]
    POLAR_PLUS_YEARLY_PRODUCT_ID: ENC[AES256_GCM,data:KS3WvvU/FjmUsubjCa4+vxq4nfXlzcBKtXCAwVxiTBrLpVZL,iv:BeDjM9unTxjEvTjfwPMyu7hl9HyTAuOzXdyDSdN6dRE=,tag:9wcHwuINMSmYNds5946L7g==,type:str]
    POLAR_SERVER: ENC[AES256_GCM,data:PM7G9KxCASR60A==,iv:4AWjnyIZrguZ7veuzPyPr4uNzd4wY7Ncpv0nygcQtic=,tag:qzxIHIP3/Nvr4jrz3DNMTA==,type:str]
    POLAR_WEBHOOK_SECRET: ENC[AES256_GCM,data:+vaCQMaLJEnvUIrBzUFp14JPg5szS7Gbkbx6z8F/tFo1XiD/mtM0ZpHohuBudpwV7nYXuYc=,iv:+5ty8q+IRZ5cIKTWzUkNJsevlqrCRz6FCvqqRmuleHM=,tag:TLIFjpedcFreTbOVb9AfGg==,type:str]
    PUBLIC_POSTHOG_KEY: ENC[AES256_GCM,data:v2M9jtX9KieSYR9nESVGzziUR0IDDfuLwUs9WRCr8I2q0HkyVvhq86YatFJ1PK8=,iv:3e61R4TmTugosoyPGGsAk9N5g10tqjQl4dditp7ImY4=,tag:a8/bNfknvS9ZEqTW9qdUmA==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:8Po7n4dfdXnyuwfQEDyfPHv4cCE9NJyZQvW0esW8qh0XZo1g,iv:3eHBjU+fCyQB8zGF+5P7TplZOUrsu6NnjlomnkzNsrw=,tag:KnDHni1qdoQGQe2j3N7new==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndUlPSEg1eUFBSGhIanln
            dHlSR01GYjJkVzdJeDNPdlFocGZ4d0V1UmxRCkp2MzZLOG43L3hna0VXZWVRaTNR
            WlJCdCt5SnBhN2tFYkxoL0hBMVRzQ0EKLS0tIDR4Z0tTaHVjbTJ3bVVTeGNIcERC
            WThVbWtuWHNqQTRrSEpXOTZUQ2YxbTAKtOjDtZA4CFebA60+qFm1QoN4Y3Jp+ruV
            0GVkypXqIBajk2/9U9cBAsZlYfQuVc9uvcEKk5s+8VUOs1D8phTqWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T04:12:56Z"
    mac: ENC[AES256_GCM,data:u5MiFpp/6GoFksJdKQvE0u6cdATWY5H7vNAExiCk2D8Q1oMcsJTGvu5csnlAF3eYTSDszNLLF1I/pIB8ptz7WLMWEJELcuqdq2SoL8JvOJ47fLIjhmSOMsxLp5p8jsnbsdvpp9BbE372CToGYsIORMb9nwk3C+t+boMVlI7bA80=,iv:9m2ztX9GQfFMQERBtd9m/Gt1Hkhws25WdSstDSf7xN0=,tag:FrVa8ObyfAJQHTidPnarGw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: plarza-libsql-auth
    namespace: plarza
type: Opaque
stringData:
    SQLD_AUTH_JWT_KEY: ENC[AES256_GCM,data:/2sLKWw+sp+pdWeR62arn5OrSXey2BrQua924JfZFmiJxWUlTSa2G1mN6Sjy3WGw8RsOHkINmnVOt9U4FvM41C4YzKaRF8Vk5WmB4hR1F3iCAzjwbVCkrasZ/5gBnbyy2Rm57yvoPBTrKlwDC7KYxg8=,iv:Fnf1PcM+6BZN4kwFu9wzUPwrcWpQXVpEPni8C2rH0Qk=,tag:/dc4rBoKl/PT76Wg4Rr8hg==,type:str]
    SQLD_AUTH_JWT_PRIVATE_KEY_PEM: ENC[AES256_GCM,data:7fpU6vxJYoxeDig8LKHBEcik3QF2IJfwGz9yvNvkXyw4ttGXyD2db/SxVjf4roGFh6oUr6l8Ov53Eoo0BH/bF7gQTZ1aIJz3uNvaw78xJqio1V0ynhgpeFQ9tBeYbOS153BshSZPgNbROinyAqRNuiMG85FOt/k=,iv:ZHSqpb/v2zcwxOSIF/96cSIvmWby6byEegkLAS+jB3Q=,tag:TDqMdHzZn/fadGJyf7Gt4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndUlPSEg1eUFBSGhIanln
            dHlSR01GYjJkVzdJeDNPdlFocGZ4d0V1UmxRCkp2MzZLOG43L3hna0VXZWVRaTNR
            WlJCdCt5SnBhN2tFYkxoL0hBMVRzQ0EKLS0tIDR4Z0tTaHVjbTJ3bVVTeGNIcERC
            WThVbWtuWHNqQTRrSEpXOTZUQ2YxbTAKtOjDtZA4CFebA60+qFm1QoN4Y3Jp+ruV
            0GVkypXqIBajk2/9U9cBAsZlYfQuVc9uvcEKk5s+8VUOs1D8phTqWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T04:12:56Z"
    mac: ENC[AES256_GCM,data:u5MiFpp/6GoFksJdKQvE0u6cdATWY5H7vNAExiCk2D8Q1oMcsJTGvu5csnlAF3eYTSDszNLLF1I/pIB8ptz7WLMWEJELcuqdq2SoL8JvOJ47fLIjhmSOMsxLp5p8jsnbsdvpp9BbE372CToGYsIORMb9nwk3C+t+boMVlI7bA80=,iv:9m2ztX9GQfFMQERBtd9m/Gt1Hkhws25WdSstDSf7xN0=,tag:FrVa8ObyfAJQHTidPnarGw==,type:str]
    version: 3.13.1
